spring.application.name=taskManagementService

database.cluster=dumontt.fg9m4bn.mongodb.net
database.username=dumontt
database.dbname=taskdb
database.password=HemanDON1

logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG

mongo.db.test.url=mongodb://localhost:27080
mongo.db.test.enabled=false