spring.application.name=taskManagementService

database.cluster=<YOUR_CLUSTER>
database.username=<YOUR_USERNAME>
database.dbname=<YOUR_DBNAME>
database.password=<YOUR_PASSWORD>

logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG

mongo.db.test.url=mongodb://localhost:27080
mongo.db.test.enabled=false