spring.application.name=taskManagementService

# 2. Propriedades Personalizadas (Opcional, se você for usá-las na sua configuração manual)
# Use 'taskdb' como o nome do banco de dados (Task Management -> taskdb)
database.cluster=dumontt.fg9m4bn.mongodb.net
database.username=dumontt
database.dbname=taskdb
database.password=HemanDON1

# 3. Logs de Debug
logging.level.org.springframework.data.mongodb.core=DEBUG
logging.level.org.springframework.boot.autoconfigure.mongo=DEBUG

mongo.db.test.url=mongodb://localhost:27080
mongo.db.test.enabled=false